apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  replicas: 1 #3 pods
  selector:
    matchLabels:
      app: micro1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
        - name: micro1
          image: 637423361057.dkr.ecr.us-east-2.amazonaws.com/micro1:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: micro1-service
spec:
  selector:
    app: micro1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer