spring:
  datasource:
    username: admin
    password: admin123
    url: <...>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: <...>
        secret-key: <...>
      region:
        static: us-east-2
      sqs:
        endpoint: <...>


